# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncoms.proto\"\x1e\n\x07ModeSet\x12\x13\n\x04mode\x18\x01 \x01(\x0e\x32\x05.Mode\"+\n\x08MotorSet\x12\x0c\n\x04port\x18\x01 \x01(\x02\x12\x11\n\tstarboard\x18\x02 \x01(\x02* \n\x04Mode\x12\n\n\x06MANUAL\x10\x00\x12\x0c\n\x08WAYPOINT\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODE._serialized_start=91
  _MODE._serialized_end=123
  _MODESET._serialized_start=14
  _MODESET._serialized_end=44
  _MOTORSET._serialized_start=46
  _MOTORSET._serialized_end=89
# @@protoc_insertion_point(module_scope)
